appName: currencyservice
appImage: alexzhenyul/currencyservice
appVersion: latest
appReplicas: 2
containerPort: 7000
containerEnvVars:
  - name: PORT
    value: "7000"

serviceType: ClusterIP
servicePort: 7000