appName: emailservice
appImage: alexzhenyul/emailservice
appVersion: latest
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"    

servicePort: 5000