---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-viewer-binding
roleRef:
  kind: ClusterRole
  name: viewer      # specify which role to bind
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: my-viewer     # my-viewer RBAC group
    apiGroup: rbac.authorization.k8s.io